USB_VID = 0x239A
USB_PID = 0x807E
USB_PRODUCT = "Feather with LCD"
USB_MANUFACTURER = "Oddly Specific Objects"

CHIP_VARIANT = SAML22J18A
CHIP_FAMILY = saml22

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

SUPEROPT_GC = 0
